/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Display.java
 *
 * Created on 11/Abr/2011, 15:38:02
 */

package iart;

import java.util.Vector;
import javax.swing.JScrollPane;
import org.jgraph.JGraph;

/**
 *
 * @author Diogo
 */
public class Display extends javax.swing.JFrame {
    
    public double ticket_price;

    public static Vector<BusStop> busStops = new Vector<BusStop>();
    public static Vector<String> buses = new Vector<String>();
    public static MyGraph mg = new MyGraph();
    public static JGraph jgraph;

    /** Creates new form Display */
    public Display() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });*/
        
        Config c = new Config();
        c.load();
        printFrames();


        //graph
        mg.init();

        //adicionar vertices
        for (int i = 0; i < busStops.size(); i++) {
            mg.addVertex(busStops.get(i).getName(), busStops.get(i).getXCoord(), busStops.get(i).getYCoord());
        }

        //adicionar arestas
        for (int i = 0; i < busStops.size(); i++) {
            String origin = busStops.get(i).getName();
            Vector<String> neighbors = busStops.get(i).getNeighbors();

            for (int j = 0; j < neighbors.size(); j++) {
                mg.addEdge(origin, neighbors.get(j));
            }
        }

        mg.show(true);

        jgraph = mg.getJGraph();

        displayRoute(-1);

    }




    /**
     * Mostra no grafo o trajecto do autocarro na posição 'index'
     * Mostra todos os trajectos se index = -1
     * @param index: posiçao do autocarro cujo trajecto se pretende mostrar
     */
    public static void displayRoute(int index) {
        if (index < -1 || index >= buses.size()) {
            return;
        }

        if (index == -1) {
            for (int i = 0; i < busStops.size(); i++) {
                String origin = busStops.get(i).getName();
                Vector<String> neighbors = busStops.get(i).getNeighbors();

                for (int j = 0; j < neighbors.size(); j++) {
                    mg.addEdge(origin, neighbors.get(j));
                }
                return;
            }
        }

        String busID = buses.get(index);
        Vector<String> route = new Vector<String>();

        //encontrar o ponto de partida do autocarro
        for (int i = 0; i < busStops.size(); i++) {
            if (busStops.get(i).isBusFirstStop(busID)) {
                //encontrar o resto do percurso
                busStops.get(i).getBusRoute(busID, route);
                break;
            }
        }


        //mostra no grafo o trajecto encontrado
        mg.resetEdges();

        for (int i = 1; i < route.size(); i++) {
            mg.addEdge(route.get(i - 1), route.get(i));
        }

    }

    /**
     * Actualiza a informação do horário de uma paragem já existente
     * @param busStopID: id da paragem a actualizar
     * @param busID: id do autocarro cujo horário se pretende actualizar
     * @param bsi: informação do horário
     */
    public static void addBusStopInfo(String busStopID, String busID, BusStopInfo bsi) {

        for (int i = 0; i < busStops.size(); i++) {
            if (busStops.get(i).getName().equals(busStopID)) {

                busStops.get(i).addBusStopInfo(busID, bsi);
                return;
            }
        }

        System.out.println("ERRO: Paragem '" + busStopID + "' não encontrada.");
        System.exit(1);
    }

    /**
     * Actualiza o nome do autocarro busID, dando-lhe o nome da paragem terminal como sufixo
     * 804 -> 804-S.João
     * @param busID nome do autocarro
     * @param busTerminal sufixo
     */
    public static void fixBusName(String busID, String busTerminal) {

        for (int i = 0; i < busStops.size(); i++) {
            busStops.get(i).fixBusName(busID, busID + "-" + busTerminal);
        }
    }

    /**
     * Imprime as frames
     */
    public static void printFrames() {
        for (int i = 0; i < busStops.size(); i++) {
            busStops.get(i).printFrame();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JFrame jFrame2;
    private static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
